# #第一阶段 Node 镜像：使用 node 镜像对单页应用进行构建，生成静态资源。
FROM node:latest as builder

WORKDIR /code

# 单独分离 package.json，是为了安装依赖可最大限度利用缓存
ADD package.json yarn.lock /code/
# 如果 yarn.lock 内容没有变化，则不会重新依赖安装
RUN yarn 

ADD . /code
RUN yarn build


# #第二阶段选择更小体积的基础镜像
FROM nginx:alpine
COPY --from=builder code/build /usr/share/nginx/html

EXPOSE 3000